[build]
# zig = true

# pre-build = [
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update && apt-get install --assume-yes make:$CROSS_DEB_ARCH g++:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH",
# ]
# pre-build = [
#     "dpkg --print-architecture",
#     "dpkg --add-architecture armhf",
#     "apt update && apt install --assume-yes g++:armhf libfontconfig1-dev:armhf libfontconfig-dev:armhf libssl-dev:armhf libxcb-shape0-dev:armhf libxcb-xfixes0-dev:armhf",
# ]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
  "dpkg --add-architecture armhf",
  "apt-get update",
  "apt-get install --assume-yes libfontconfig-dev:armhf libglib2.0-dev:armhf",
]

[target.armv7-unknown-linux-gnueabi]
pre-build = [
  "dpkg --add-architecture armhf",
  "apt-get update",
  "apt-get install --assume-yes libfontconfig-dev:armhf",
]


[target.armv7-unknown-linux-musleabihf]
pre-build = [
  "export DEBIAN_FRONTEND=noninteractive",
  "dpkg --add-architecture armhf",
  # "dpkg --add-architecture arm64",
  "apt-get update",
  # "apt-get install -yq libssl-dev:arm64 libfontconfig-dev:arm64 libfontconfig1:arm64 libfontconfig1-dev:arm64",
  "apt-get install -yq libfontconfig-dev:armhf libfontconfig1:armhf libfontconfig1-dev:armhf libglib2.0-dev:armhf",
  # "apt-get install -yq pkg-config libfontconfig-dev libfontconfig1 libfontconfig1-dev",
]
  # "apt-get update",
  # "apt-get install --assume-yes:armhf libfontconfig-dev:armhf fontconfig:armhf librust-servo-fontconfig-dev:armhf librust-servo-fontconfig-sys-dev:armhf librust-yeslogic-fontconfig-sys-dev:armhf librust-crossfont+force-system-fontconfig-dev:armhf",


[target.armv7-unknown-linux-musleabi]
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update",
  "apt-get install --assume-yes libfontconfig-dev:arm64 libglib2.0-dev:arm64",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update",
  "apt-get install --assume-yes libfontconfig-dev:arm64",
]


