on: [push]

name: Cross-platform check

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1

      - name: Patch azure linux deps
        run: sudo apt update
        if: matrix.os == 'ubuntu-latest'

      - name: Install linux deps
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev libasound2-dev meson ninja-build libdav1d-dev dav1d
        if: matrix.os == 'ubuntu-latest'


      - name: Update Rust
        run: rustup update
        if: matrix.os == 'ubuntu-latest'
        
      - name: Install osx deps
        run: brew install meson ninja
        if: matrix.os == 'macos-latest'

      # - name: Install win ninja
      #   run: choco install ninja
      #   if: matrix.os == 'windows-latest'

      - name: Install win Dav1d
        run: vcpkg install dav1d:x64-windows
        if: matrix.os == 'windows-latest'

      # - name: Install win meson
      #   run: python -m pip install meson
      #   if: matrix.os == 'windows-latest'

      - name: cargo build 
        run: cargo build

      - name: cargo check without default features
        run: cargo check --no-default-features

