on: [push]




name: Cross-platform check
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, windows-2019, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'
        
      - name: Configure pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        if: matrix.os == 'windows-latest' || matrix.os == 'windows-2019'
        
      - name: Set up pagefile
        run: |
          (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
        if: matrix.os == 'windows-latest' || matrix.os == 'windows-2019'
        
      - name: Patch azure linux deps
        run: sudo apt update
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'

      - name: Install linux deps
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev libasound2-dev
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'

      - name: Update Rust
        run: rustup update
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'
        
      - name: Install osx deps
        run: brew install nasm
        if: matrix.os == 'macos-latest'

      - name: cargo build 
        run: cargo build --features jpgxl

      - name: cargo check without default features
        run: cargo check --no-default-features

