on: [push]

name: Check Ubuntu
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - uses: Swatinem/rust-cache@v2

        
      - name: Patch azure linux deps
        run: sudo apt update

      - name: Install linux deps
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev libasound2-dev

      - name: Update Rust
        run: rustup update

      - name: build heif
        run: ./build_deps_linux.sh

      - name: install heif
        run: cd libheif/build && sudo make install

      # - name: cargo build 
      #   run: cargo build

      - name: cargo check without default features
        run: cargo check --no-default-features

      - name: cargo check without build features
        run: PKG_CONFIG_PATH=libheif/build cargo check --features heif

