on: [push]

name: Check OSX
jobs:
  check:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1

      # - name: cargo build 
      #   run: cargo build

      - name: Check without default features
        run: cargo check --no-default-features

      - name: Check without build features
        run: cargo check --features heif

      - name: Run buildscript
        run: ./build_mac.sh