name: Check NetBSD minimal

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test in NetBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1.0.5
      with:
        usesh: true
        copyback: false
        prepare: |
          /usr/sbin/pkg_add curl pkg-config cmake openssl libX11 fontconfig freetype2 gdk-pixbuf2 cairo pango atk glib2 libXrender libxcb nasm perl git python39 ninja
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        run: |
          PATH=$HOME/.cargo/bin:$PATH
          export PATH
          cargo check --no-default-features  --features notan/glsl-to-spirv
