on: [push]

name: Check Windows
jobs:
  check:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - uses: Swatinem/rust-cache@v2
      
      - name: Install vcpkg
        run: vcpkg integrate install

      - name: Install Ninja
        run: choco install ninja

      # - name: Install Vulkan SDK
      #   uses: humbletim/install-vulkan-sdk@v1.1.1
      #   with:
      #     cache: true

      - name: Install libheif
        run: vcpkg install libheif:x64-windows-static-md

      - name: Install libheif static
        run: vcpkg install libheif:x64-windows-static

      - name: cargo check without default features
        run: cargo check --no-default-features

      - name: clean
        run: cargo clean

      - name: cargo check build features
        run: cargo check --features heif